local options = {
  ensure_installed = {
    "awk",
    "bash",
    "c",
    "c_sharp",
    "clojure",
    "cmake",
    "commonlisp",
    "cpp",
    "css",
    "csv",
    "d",
    "dart",
    "devicetree",
    "diff",
    "dockerfile",
    "dot",
    "doxygen",
    "dtd",
    "elixir",
    "erlang",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitignore",
    "go",
    "gpg",
    "graphql",
    "hack",
    "haskell",
    "haskell_persistent",
    "html",
    "http",
    "java",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "kotlin",
    "latex",
    "llvm",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "markdown_inline",
    "matlab",
    "meson",
    "nim",
    "nim_format_string",
    "ninja",
    "objc",
    "objdump",
    "ocaml",
    "ocamllex",
    "pascal",
    "perl",
    "php",
    "phpdoc",
    "pod",
    "proto",
    "psv",
    "python",
    "r",
    "racket",
    "regex",
    "ruby",
    "rust",
    "scala",
    "scss",
    "sql",
    "ssh_config",
    "strace",
    "svelte",
    "swift",
    "tcl",
    "terraform",
    "tmux",
    "toml",
    "typescript",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zig",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = { enable = false },
  autopairs = { enable = true },
  playground = { enable = true },
}

return {
  {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    config = function()
      return options
    end,
  },

  -- Treesitter playground
  {
    "nvim-treesitter/playground",
    cmd = { "TSPlaygroundToggle" },
    dependencies = {
      "nvim-treesitter",
    },
  },
}
